### PR TITLE
PostgreSQL 16.1 Release

### PR DESCRIPTION
**Pull request by adeherdt-r7**
## Description

This is the change in scripts to install the 16.1 version of PostgreSQL, bumping the version where needed.

This is my first time working with Chocolatey packages, so I'm not all too familiar with the entire procedure.
If additional work needs to be made, please let me know and I'll be happy to resolve any open issues.

If this works out fine, I'm happy to make additional pull-requests for the remaining versions and release them one by one.

### CODE REVIEW

**Comment by majkinetor** [comment]
It can't be done that way. This is automatic package that supports postgresql streams and it requires fix within AU routine or even CI/CD.

I can't get [this error](https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#ignored) locally, and its the only reason we don't have the updates. Perhaps it requires different type of Windows machine on AppVeyor or even switching everything to GitHub Actions. 

If you want to do any of it, I can review the code, but I don't currently have time to do it on my own.

**Comment by majkinetor** [comment]
BTW, this happens for some time and when I needed the newer version on my own projects I simply run the AU updater locally and pushed packages it created manually (since the error doesn't show locally).

**Comment by adeherdt-r7** [comment]
> I can't get [this error](https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#ignored) locally, and its the only reason we don't have the updates. Perhaps it requires different type of Windows machine on AppVeyor or even switching everything to GitHub Actions.
> 
> If you want to do any of it, I can review the code, but I don't currently have time to do it on my own.

I've been reading through the entire discussion that is linked to this, and Windows Server 2012 definitely might be part of the problem, because the core issue is TLS cyphers and no secure connection established.
So jumping to higher version of Windows Server on AppVeyor will at least fix that pipeline.

> It can't be done that way. This is automatic package that supports postgresql streams and it requires fix within AU routine or even CI/CD.

I'll need some explanation on what I need to do to make all this work correctly.
I'm more than happy to put in the effort, but I have no experience with creating Chocolatey packages.
Mind if you can guide me through this once, I can probably do the work alone for all following versions.

**Comment by majkinetor** [comment]
This is used now

image

This is available:

image

**Comment by majkinetor** [comment]
> but I have no experience with creating Chocolatey packages.

You not only need to have experience in Choco but in AU and general automation too. 


In any case, I will try some other images and see if error disappears.

**Comment by adeherdt-r7** [comment]
Yeah selecting a higher Visual Studio version should be the trick.
At least if I read the AppVeyor documentation correctly.

Feel free to ping me, if you need anything from my side to be done.

**Comment by majkinetor** [comment]
Nah, its the same. Tried VS 2022 and VS 2013

**Comment by adeherdt-r7** [comment]
:/ shame

Then I'll keep an eye on the other discussion and see what their recommendation etc is going to be.

**Comment by majkinetor** [comment]
I suggest converting CI-CD to GitHub Actions.

This problem was present on AV all the time, for various packages. Funny, sees only PG is now affected

**Comment by majkinetor** [comment]
image

**Comment by adeherdt-r7** [comment]
Yeah, changing the protocol doesn't seem to help on either run.
Still waiting on feedback from the upstream.

**Comment by majkinetor** [comment]
I will see to move it to the GitHub actions myself.

**Pull request closed without merging**
