### PR TITLE
Change Nicotine+ author to Nicotine+ Team

### PR DESCRIPTION
**Pull request by mathiascode**
Thanks for packaging Nicotine+ for Chocolatey!

If possible, I wound prefer it if the package listing didn't include my username.

### CODE REVIEW

**Comment by majkinetor** [comment]
Of course.

I will repush the package. Thx for PR.

**Comment by majkinetor** [comment]
Its up. Nobody will see the previous author as it wasn't approved yet (and there is a good chance it wont be, not sure if ticket link is enough for choco admins, given that there are 6 positives):

image

**Comment by mathiascode** [comment]
No worries, I'm mainly trying to avoid any additional situations where the software is listed under usernames of former developers.

I can't promise that the false positives of the 32-bit version will be possible to resolve in the near future, but perhaps the 32-bit version can be excluded temporarily, if necessary.

**Comment by majkinetor** [comment]
Yes, I will remove it from the package if there is no good response.

**Comment by majkinetor** [comment]
FYI, this is automatic package, it will be available with less then 1 day latency using GH releases.

**Comment by majkinetor** [comment]
FYI, package is approved totally, and now can be used regularly. Its exempted from virus check as I provided more info on the problem.

**Pull request merged**
